### PR TITLE
[14.0][ADD] account_consolidation_oca: add new module

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago @etobella @pedrobaeza @douglascstd @augustodinizl 

- This module is a rename of account_consolidation, therefore, part of a migration based on commit histories [[14.0] account_consolidation: Migration to 14.0](https://github.com/OCA/account-consolidation/pull/38) referring to the past branch, due to name conflicts it now becomes account_consolidation_oca

Adapted some functionalities to be used as auto_post instead of the no longer present auto_reverse in addons account.

Due to pylint detecting duplicate ID for the demo consolidation_company when accessing the consolidation account, please go to:

- Settings -> Invoicing -> Consolidation
- Choose "Consolidation differences" as "CED Consolidation Exchange Differences"
- Choose "Consolidation journal" as "Consolidation journal." 

Below is a screenshot of how it should look like.

Captura de tela de 2023-06-24 03-24-53

### CODE REVIEW

**Comment by etobella** [comment]
Commit history has not been kept. Can you use my branch?

https://github.com/dixmit/account-consolidation/tree/14.0-consolidiation 

After the filter-branch, you needed to do a git rebase

**Comment by kaynnan** [comment]
.

**Comment by kaynnan** [comment]
.

**Comment by kaynnan** [comment]
> Commit history has not been kept. Can you use my branch?
> 
> 
> 
> https://github.com/dixmit/account-consolidation/tree/14.0-consolidiation 
> 
> 
> 
> After the filter-branch, you needed to do a git rebase

@etobella The same conflict occurred as the previous pr, after filtering and sending the pr it closed claiming that there were unmerged commits, what can I do to resolve it?

**Comment by pedrobaeza** [comment]
You have to rebase against origin/14.0 after doing such operation (`git filter-branch`).

**Comment by kaynnan** [comment]
I understand, I believe I rebase on Origin/14.0, if I rebase again will the pull request return to normal?

**Comment by etobella** [comment]
I don't know, maybe you will need to open a new PR :sob:

**Comment by pedrobaeza** [comment]
You can try to do the operation and push force to see if the button "Reopen and comment" is available, but I think it won't be. Why not starting from the branch https://github.com/dixmit/account-consolidation/commits/14.0-consolidiation that @etobella has prepared to you?

**Comment by kaynnan** [comment]
Well, I can try this, if the button is not available I will start with the branch, I believe I will create the pr by the end of the day, thanks for the help guys

**Comment by kaynnan** [comment]
.

**Pull request closed without merging**
